image: Visual Studio 2017

platform:
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 12 x86
  - npm install
  - npm run rebuild

build_script:
  - npm run release
